### ISSUE TITLE
Implement Literals

### ISSUE THREAD

**Issue by jb55** [jb55/btcs#3]
Perhaps `0xabcdef0123456789` for pushing data. Arbitrary hex strings without the prefix should be possible as well. What about decimal integers/ScriptNums? Strings?

Full support for many types of literals would be nice.

- [x] #13 ~~Number literals~~
- [x] #11 Data literals
- [x] #18 String literals

**Comment by jb55** [comment]
Also should it automatically add the pushdata ops? Syntax for explicit and implicit pushdata? Perhaps a prefix for surpressing op creation, since implicit pushdata would be the more common use case I think? And you could guarantee minimal pushes with implicit ops which is a nice default.

Still not sure yet, will see how it feels when it's implemented.

**Comment by jb55** [comment]
Cc @fivepiece

**Comment by fivepiece** [comment]
hey @jb55 , the way I see it as being intuitive as possible is :

* Numbers are the most important, because they're also the most confusing in script imo.  I believe the most useful syntax is just the natural base 10 one.  In my serializer, you write numbers just as you would outside script, so e.g. `10385` is translated to `029128` and `-10385` to `0291A8`.
This is also the way core does it.

* Pushdata is next, I use `@` in front of a hex value, so `@AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` becomes `15AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`.
`@` has to know about longer and shorter push values, so e.g.
```
@AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```
Becomes
```
4C80AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
```

Also, for the lower values, it's important that `@` knows about the numbers from above, but in a different way, since it expects hex. `@16` is `0116`, but `@10` is just `60`.  Likewise `@81` is `4F`.

* Literal script elements are also useful, anything prefaced with `0x` which is a valid length hex data is just serialized literally.  Core does this too.

* One option I chose not to implement is `'<text>` into a push of text in hex.  It's not very interesting to me.

Cheers

**Comment by jb55** [comment]
@fivepiece

> Also, for the lower values, it's important that `@` knows about the numbers from above, but in a different way, since it expects hex. `@16` is `0116`, but `@10` is just `60`.  Likewise `@81` is `4F`.

Would it make sense to just keep 0x to always mean a hex value in either
scriptnum or pushdata context? Then you could just do @10 to mean push
the decimal number 10 as data and @0x10ff to mean push the hex value 0x10ff as
data. This would be more in-line with what programmers are used to.

> * Literal script elements are also useful, anything prefaced with `0x` which is a valid length hex data is just serialized literally.  Core does this too.

Hmm this might still work with my above suggestion, but would fail in
the case where you want to use push a hex scriptnum.

What do you mean core does this? I did notice that in
`vout.scriptPubKey.asm` they show something along the lines of:

    OP_DUP OP_HASH160 5fc1015d24801c18a3760ba48e555fe1189b4d23 OP_EQUALVERIFY OP_CHECKSIG

where `5fc1015d24801c18a3760ba48e555fe1189b4d23` is a pretty-printed
pushdata of length 20. It would be really cool if you could just copy
and paste this into btcs. Right now you would have to convert it to
something like:

    OP_DUP OP_HASH160 @0x5fc1015d24801c18a3760ba48e555fe1189b4d23 OP_EQUALVERIFY OP_CHECKSIG

or

    OP_DUP OP_HASH160 @5fc1015d24801c18a3760ba48e555fe1189b4d23 OP_EQUALVERIFY OP_CHECKSIG

perhaps we could interpret long hex strings as implicit pushdata. It's
really only ambiguous for the smaller values.

Some ideas for consistent literal syntax

    0xa       OP_DUP OP_ADD # interpreted as hex number
    @424242   OP_HASH160    # interpreted as decimal pushdata (is this useful?)
    @0xffff   OP_HASH160    # interpreted as hex pushdata
    @ffff     OP_HASH160    # implicit hex pushdata? (maybe bad idea)
    abcdef123 OP_HASH160    # implicit hex pushdata? (maybe bad idea)
    @ab123bcd OP_HASH160    # implicit hex pushdata? (maybe bad idea)
    "hey"     OP_HASH160    # implicit string push data
    @"hey"    OP_HASH160    # explicit string push data (redundant?)
    ff        OP_HASH160    # abiguous? probably bad idea.
    "hey"     OP_HASH160    # string push data
    10        OP_HASH160    # interpreted as scriptnum
    10        OP_DUP OP_ADD # interpreted as scriptnum

Some ideas for literal serialization (is this useful? I guess it's like
asm blocks in c/c++):

    OP_NOP [76a914f56f8e0778cb7a9542a820c273c83342178ec94588ac] OP_NOP

anyways, my goal is to have a somewhat reasonable syntax with consistent
symantics. Not sure if any of these makes sense since I'm not 100% up to
speed on bitcoin script yet.

> * One option I chose not to implement is `'<text>` into a push of text in hex.  It's not very interesting to me.

Would be useful for those `OP_RETURN "Hey I'm in the blockchain"` scripts.

> Cheers

Thanks!

**Comment by fivepiece** [comment]
@jb55,  

Let's first agree that any value which is not an opcode requires a pushdata op.  On top of that, script validation requires some standardness rules because many times it's possible to accomplish the same script execuition by manipulating pushops.

I'll be using the output from 
`bitcoin-tx -json -create outscript=0:"<script>"`
and explain how I try to be compatible with it.

For example, you have this normal p2pkh script :
`DUP HASH160 0x14 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF EQUALVERIFY CHECKSIG`

`bitcoin-tx` will recognize a scriptpubkey of type `pubkeyhash`.  Makes sense, but what about :
`DUP HASH160 0x4C 0x14 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF EQUALVERIFY CHECKSIG`

Here we added the PUSHDATA1 opcode, which means that the byte after it `0x14`, contains the size of the element to be pushed.  It's redundant, it'll cost 1 more byte in transaction data, but it works just the same.

Also :
`DUP HASH160 0x4D 0x1400 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF EQUALVERIFY CHECKSIG`

And :
`DUP HASH160 0x4E 0x14000000 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF EQUALVERIFY CHECKSIG`

Which do the same thing using PUSHDATA2 and PUSHDATA4.  You can even see that `bitcoin-tx` still parses this scriptpubkey as a p2pkh type.  It's not so bad when things like this might exist in transaction outputs' scripts, but they become an annoyance when done by third parties in scriptsig.
This is why minimal push is standardness rule, which means that you always have to use the minimal push op for the data.
This is also the use I have for the `@` character in my serializer.  All it does is chooses the correct pushop for the **hex** data appended to it.

Numbers in script are also just hex values that are pushed on the stack, but they have a bunch more rules to them.
Specifically the numbers `[1..16]` and `-1` are to be pushed by an opcode specific to them.  That is, if for example you'd want to push the number `01` to the stack, you would need to do so with the opcode `51` and not `0101` (although they produce the same result, the latter is non standard).
So considering all of that, plus how non intuitively numbers are encoded in script (endianess, negative sign), it makes sense that folks would be inputting numbers in "human" base 10 and that the conversion to the right format will be done by the interpreter, which is what `bitcoin-tx` does.
You can try stuff like `outscript=1:"-1"` , `outscript=1:"4", `outscript=1:"7777" and so on to see how it handles stuff.

The point I'm trying to make is that there should be a single correct way to push any piece of data onto the stack, and that giving away too much freedom by enabling composition of `@` and `0x..` is too ambigous imo, and would probably result in many non standard pushes.

Core doesn't have an operator like `@` to help with pushing data, so you always have to specify all sizes yourself.  That's the use case behind `@` for me.
If you really want to include hex that would not be pushed and just executed as is, that's where `0x<hex>` comes in.

As for pushing "hexlified" text like in your op_return example, basically I find that op_return <data> is the most boring script of all, because it does absolutely nothing and just creates spam on chain, so I chose not to bother with it :)

**Comment by jb55** [comment]
@fivepiece thanks, that clears up a bunch of things! I'm going to tackle this soon after I finish implementing the OPs.

**Comment by jb55** [comment]
number literals are implemented now!

**Comment by jb55** [comment]
Initial data literals finished in 25ccf3328c9ba80c12a981ecabda89afbd7a29d2

**Comment by jb55** [comment]
done for now
